tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.services.synthetic_bot_browser_chat.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  models:
    bb3_3B:
      model_file: zoo:bb3/bb3_3B/model
      interactive_mode: True
      no_cuda: False
additional_args:
  page_id: 1 # Configure Your Own Page
