tasks:
  default:
    onboard_world: SyntheticBotOnboardWorld
    task_world: SyntheticBotTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.services.synthetic_bot_browser_chat.worlds
overworld: SyntheticBotOverworld
max_workers: 30
opt:
  debug: True
  models:
    bb3_3B:
      model_file: /home/moe/Documents/GitHub/ParlAI/data/models/bb3/bb3_3B/model
      interactive_mode: True
      no_cuda: False
      override:
        init_opt: gen/bb3_3B
        serializable_output: True
        sdm_beam_block_ngram: -1
        sdm_beam_min_length: 1
        sdm_beam_size: 1
        sdm_history_size: 1
        sdm_inference: greedy
        search_decision: never
        search_decision_control_token: __is-search-required__
        search_decision_do_search_reply: __do-search__
        search_decision_dont_search_reply: __do-not-search__

        mdm_beam_block_ngram: -1
        mdm_beam_min_length: 1
        mdm_beam_size: 1
        mdm_history_size: -1
        mdm_inference: greedy
        mdm_model: projects.bb3.agents.r2c2_bb3_agent:BB3SubSearchAgent
        memory_decision: compute
        memory_decision_control_token: __is-memory-required__
        memory_decision_do_access_reply: __do-access-memory__
        memory_decision_dont_access_reply: __do-not-access-memory__
        memory_decision_use_memories: True

        search_query_control_token: __generate-query__
        search_server: relevant_search_server

        sgm_beam_block_ngram: -1
        sgm_beam_min_length: 2
        sgm_beam_size: 1
        sgm_inference: beam
        sgm_model: projects.bb3.agents.r2c2_bb3_agent:BB3SubSearchAgent

        memory_generator_control_token: __generate-memory__
        mgm_beam_block_ngram: 3
        mgm_beam_min_length: 10
        mgm_beam_size: 3
        mgm_inference: beam
        mgm_history_size: 1
        mgm_model: projects.bb3.agents.r2c2_bb3_agent:BB3SubSearchAgent

        memory_knowledge_control_token: __access-memory__
        mkm_beam_block_ngram: 3
        mkm_beam_context_block_ngram: -1
        mkm_beam_min_length: 5
        mkm_beam_size: 3
        mkm_inference: beam
        mkm_model: projects.bb3.agents.r2c2_bb3_agent:BB3SubSearchAgent
        mkm_rag_retriever_type: search_engine
        mkm_search_query_generator_model_file: ''
        mkm_search_server: 
        mkm_memory_retriever: True

        contextual_knowledge_control_token: __extract-entity__
        ckm_beam_block_ngram: 3
        ckm_beam_context_block_ngram: 3
        ckm_beam_min_length: 1
        ckm_beam_size: 3
        ckm_inference: beam
        ckm_model: projects.bb3.agents.r2c2_bb3_agent:BB3SubSearchAgent

        search_knowledge_control_token: __generate-knowledge__
        skm_beam_block_ngram: 3
        skm_beam_context_block_ngram: 3
        skm_beam_min_length: 10
        skm_beam_size: 3
        skm_doc_chunks_ranker: woi_chunk_retrieved_docs
        skm_inference: beam
        skm_model: projects.bb3.agents.r2c2_bb3_agent:BB3SubSearchAgent
        skm_n_ranked_doc_chunks: 1
        skm_rag_retriever_type: search_engine
        skm_search_query_generator_model_file: ''

        srm_beam_block_full_context: True
        srm_beam_block_ngram: 3
        srm_beam_context_block_ngram: 3
        srm_beam_min_length: 20
        srm_beam_size: 10
        srm_inference: beam
        srm_model: projects.bb3.agents.r2c2_bb3_agent:BB3SubSearchAgent

        crm_beam_block_full_context: True
        crm_beam_block_ngram: 3
        crm_beam_context_block_ngram: 3
        crm_beam_min_length: 20
        crm_beam_size: 10
        crm_inference: beam
        crm_model: projects.bb3.agents.r2c2_bb3_agent:BB3SubSearchAgent

        mrm_beam_block_full_context: True
        mrm_beam_block_ngram: 3
        mrm_beam_context_block_ngram: 3
        mrm_beam_min_length: 20
        mrm_beam_size: 10
        mrm_inference: beam
        mrm_model: projects.bb3.agents.r2c2_bb3_agent:BB3SubSearchAgent

        grm_beam_block_full_context: True
        grm_beam_block_ngram: 3
        grm_beam_context_block_ngram: 3
        grm_beam_min_length: 20
        grm_beam_size: 10
        grm_inference: beam
        grm_model: projects.bb3.agents.r2c2_bb3_agent:BB3SubSearchAgent

        vrm_beam_block_full_context: True
        vrm_beam_block_ngram: 3
        vrm_beam_context_block_ngram: 3
        vrm_beam_min_length: 20
        vrm_beam_size: 10
        vrm_inference: beam
        vrm_model: projects.bb3.agents.r2c2_bb3_agent:BB3SubSearchAgent

        orm_beam_block_full_context: True
        orm_beam_block_ngram: 3
        orm_beam_context_block_ngram: 3
        orm_beam_min_length: 20
        orm_beam_size: 10
        orm_inference: beam
        orm_model: projects.bb3.agents.r2c2_bb3_agent:BB3SubSearchAgent

        datatype: valid
        beam_disregard_knowledge_for_srm_context_blocking: False
        beam_disregard_knowledge_for_mrm_context_blocking: False
        beam_disregard_knowledge_for_crm_context_blocking: False
        beam_disregard_knowledge_for_grm_context_blocking: False
        beam_disregard_knowledge_for_vrm_context_blocking: False
        beam_disregard_knowledge_for_orm_context_blocking: False
        exclude_context_in_skm_context_blocking: False
        exclude_context_in_mkm_context_blocking: False
        exclude_context_in_ckm_context_blocking: False
        include_knowledge_in_skm_context_blocking: True
        include_knowledge_in_mkm_context_blocking: True
        include_knowledge_in_ckm_context_blocking: False
        inject_query_string: null
        loglevel: debug
        model: projects.bb3.agents.r2c2_bb3_agent:BlenderBot3Agent
        knowledge_conditioning: combined
        contextual_knowledge_decision: compute


additional_args:
  page_id: 1 # Configure Your Own Page
